# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen",
  "k8s.io/gengo/args",
  # "sigs.k8s.io/controller-tools/pkg/crd/generator",
]

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.15.4"

# [[override]]
#   name = "k8s.io/kube-openapi"
#   revision = "0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803"

[[override]]
  name = "github.com/go-openapi/spec"
  branch = "master"

# [[override]]
#   name = "sigs.k8s.io/controller-tools"
#   revision = "9d55346c2bde73fb3326ac22eac2e5210a730207"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.15.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.4"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.3.0"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  # branch = "master" #osdk_branch_annotation
  version = "=v0.12.0" #osdk_version_annotation

[[constraint]]
  name = "github.com/storageos/go-api"
  branch = "master"

[[constraint]]
  name = "github.com/blang/semver"
  version = "v3.6.1"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "v0.31.1"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false

  [[prune.project]]
    name = "k8s.io/gengo"
    non-go = false
